FROM maven:3-jdk-8

WORKDIR /app

RUN curl -O "https://download.jboss.org/wildfly/11.0.0.Final/wildfly-11.0.0.Final.zip" \
    && unzip wildfly-11.0.0.Final.zip \
    && export JBOSS_HOME=$PWD/wildfly-11.0.0.Final
COPY . .

RUN cp comp/src/test/resources/ortolang-users.properties /app/wildfly-11.0.0.Final/standalone/configuration/ \
    && cp comp/src/test/resources/ortolang-roles.properties /app/wildfly-11.0.0.Final/standalone/configuration/ \
    && cp comp/src/test/resources/ortolang-test-11.xml /app/wildfly-11.0.0.Final/standalone/configuration/ \
    && mvn clean test -DjbossHome=/app/wildfly-11.0.0.Final -Djboss.home=/app/wildfly-11.0.0.Final