FROM maven:3.6.1-jdk-8-alpine

ENV VERSION_WILDFLY=12.0.0.Final

WORKDIR /app

RUN curl -O "https://download.jboss.org/wildfly/${VERSION_WILDFLY}/wildfly-${VERSION_WILDFLY}.zip" \
    && unzip wildfly-${VERSION_WILDFLY}.zip \
    && export JBOSS_HOME=$PWD/wildfly-${VERSION_WILDFLY}
COPY . .

RUN cp comp/src/test/resources/ortolang-users.properties /app/wildfly-${VERSION_WILDFLY}/standalone/configuration/ \
    && cp comp/src/test/resources/ortolang-roles.properties /app/wildfly-${VERSION_WILDFLY}/standalone/configuration/ \
    && cp comp/src/test/resources/ortolang-test-${VERSION_WILDFLY}.xml /app/wildfly-${VERSION_WILDFLY}/standalone/configuration/standalone.xml \
    && mvn clean test -DjbossHome=/app/wildfly-${VERSION_WILDFLY} -Djboss.home=/app/wildfly-${VERSION_WILDFLY}