version: '2'

services:
  olrepo:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        CUSTOM_UID: '1158'
        CUSTOM_GID: '1146'
    image: ortolang-diffusion
    user: '1158:1146'
    container_name: ortolang-diffusion
    command: > 
      bash -c "cp /opt/jboss/.ortolang/config.properties /tmp/ && 
              envsubst < /tmp/config.properties > /opt/jboss/.ortolang/config.properties && 
              /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement=0.0.0.0 --debug"
    environment:
      - ORTOLANG_DB_URL=jdbc:postgresql://docker.for.mac.localhost:5432/ortolang
      - ORTOLANG_DB_USER=ortolang
      - ORTOLANG_DB_PASS=tagada54
      - ORTOLANG_HANDLE_PREFIX=114F03
      - ORTOLANG_KEYSTORE_NAME=server.keystore
      - ORTOLANG_KEYSTORE_ALIAS=server
      - ORTOLANG_KEYSTORE_PASS=tagada54
      - ORTOLANG_KEY_PASS=tagada54
      - ORTOLANG_ES_HOST=docker.for.mac.localhost
      - ORTOLANG_ES_PORT=9300
      - ORTOLANG_FTP_SERVER_HOST=localhost
      - ORTOLANG_FTP_SERVER_PORT=2221
      - ORTOLANG_FTP_SERVER_PORTS_PASV=45000-46000
      - ORTOLANG_FTP_SERVER_SSL=false
      - ORTOLANG_STATIC_SITE_VERSION=latest
      - ORTOLANG_API_URL_SSL=http://docker.for.mac.localhost:8080/api
      - ORTOLANG_API_URL_NOSSL=http://docker.for.mac.localhost:8080/api
      - ORTOLANG_AUTH_URL=http://docker.for.mac.localhost:18080/auth
      - ORTOLANG_AUTH_LOGOUT=http://docker.for.mac.localhost:18080/
      - ORTOLANG_MARKET_URL=http://docker.for.mac.localhost:8888/
      - ORTOLANG_PRERENDERING_ACTIVATED=false
      - ORTOLANG_CACHE_VERSION=1
      - ORTOLANG_SMTP_HOST=localhost
      - ORTOLANG_SMTP_PORT=587
      - ORTOLANG_SMTP_USERNAME=ortolang
      - ORTOLANG_SMTP_PASSWORD=tagada
      - ORTOLANG_SMTP_SSL=true
      - ORTOLANG_HIBERNATE_EVICTION_MAXENTRIES=5000000
      - ORTOLANG_HIBERNATE_EXPIRATION_MAXIDLE=1200000
    volumes:
      - ./ortolang-data/binary-store:/opt/jboss/.ortolang/binary-store
      - /Users/cpestel/Projets/ortolang/referentiels/00_init:/referentials
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
      - 2221:2221
      - 8787:8787
